<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.l8t5dvN' shared service.

return $this->privates['.service_locator.l8t5dvN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'repository' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService.php', true],
]);
