<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Command\BasicPageStatsCommand' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/src/Command/BasicPageStatsCommand.php';

$this->privates['App\\Command\\BasicPageStatsCommand'] = $instance = new \App\Command\BasicPageStatsCommand();

$instance->setName('BasicPage:stats');

return $instance;
