nexy_slack:

  # If you want to use an another httplug client service.
  http:
    client: httplug.client

  # The Slack API Incoming WebHooks URL.
  endpoint: https://hooks.slack.com/services/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