<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXji6ktg\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXji6ktg/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerXji6ktg.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerXji6ktg\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerXji6ktg\srcApp_KernelProdContainer([
    'container.build_hash' => 'Xji6ktg',
    'container.build_id' => '50d713a5',
    'container.build_time' => 1557529194,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXji6ktg');
