<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6lgv92z\srcApp_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6lgv92z/srcApp_KernelProdDebugContainer.php') {
    touch(__DIR__.'/Container6lgv92z.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdDebugContainer::class, false)) {
    \class_alias(\Container6lgv92z\srcApp_KernelProdDebugContainer::class, srcApp_KernelProdDebugContainer::class, false);
}

return new \Container6lgv92z\srcApp_KernelProdDebugContainer([
    'container.build_hash' => '6lgv92z',
    'container.build_id' => 'bfa55910',
    'container.build_time' => 1557531216,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6lgv92z');
