<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.p4w8ERM' shared service.

return $this->privates['.service_locator.p4w8ERM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'markdownHandler' => ['privates', 'App\\Services\\MarkdownHandler', 'getMarkdownHandlerService.php', true],
]);
