<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Services\MarkdownHandler' shared autowired service.

include_once $this->targetDirs[3].'/src/Services/MarkdownHandler.php';

return $this->privates['App\\Services\\MarkdownHandler'] = new \App\Services\MarkdownHandler(($this->services['markdown.parser'] ?? ($this->services['markdown.parser'] = new \Knp\Bundle\MarkdownBundle\Parser\Preset\Light())), ($this->services['cache.app'] ?? $this->load('getCache_AppService.php')), ($this->services['monolog.logger.markdown'] ?? $this->load('getMonolog_Logger_MarkdownService.php')), false);
