<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\BasicPageController::archive' => ['privates', '.service_locator.s4t8rZI', 'get_ServiceLocator_S4t8rZIService.php', true],
    'App\\Controller\\BasicPageController::index' => ['privates', '.service_locator.l8t5dvN', 'get_ServiceLocator_L8t5dvNService.php', true],
    'App\\Controller\\NewsAdminController::createNewsArticle' => ['privates', '.service_locator.pe89cNF', 'get_ServiceLocator_Pe89cNFService.php', true],
    'App\\Controller\\NewsController::news' => ['privates', '.service_locator.NUP9Hmn', 'get_ServiceLocator_NUP9HmnService.php', true],
    'App\\Controller\\NewsController::toggleArticleLikes' => ['privates', '.service_locator.QTfxGyi', 'get_ServiceLocator_QTfxGyiService.php', true],
    'App\\Controller\\BasicPageController:archive' => ['privates', '.service_locator.s4t8rZI', 'get_ServiceLocator_S4t8rZIService.php', true],
    'App\\Controller\\BasicPageController:index' => ['privates', '.service_locator.l8t5dvN', 'get_ServiceLocator_L8t5dvNService.php', true],
    'App\\Controller\\NewsAdminController:createNewsArticle' => ['privates', '.service_locator.pe89cNF', 'get_ServiceLocator_Pe89cNFService.php', true],
    'App\\Controller\\NewsController:news' => ['privates', '.service_locator.NUP9Hmn', 'get_ServiceLocator_NUP9HmnService.php', true],
    'App\\Controller\\NewsController:toggleArticleLikes' => ['privates', '.service_locator.QTfxGyi', 'get_ServiceLocator_QTfxGyiService.php', true],
])), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
