<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Services\SlackClient' shared autowired service.

include_once $this->targetDirs[3].'/src/Helper/LoggerTrait.php';
include_once $this->targetDirs[3].'/src/Services/SlackClient.php';

$this->privates['App\\Services\\SlackClient'] = $instance = new \App\Services\SlackClient(($this->services['nexy_slack.client'] ?? $this->load('getNexySlack_ClientService.php')));

$instance->setLogger(($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()));

return $instance;
